### ISSUE TITLE
I can't build project

### ISSUE THREAD

**Issue by kibarms** [bufferapp/clean-architecture-components-boilerplate#8]
Im use Android Studio 3.0 Beta 7 and Kotlin 1.1.51

When I want to build project I getting an error

```
Error:Execution failed for task ':cache:kaptDebugKotlin'.
> Internal compiler error. See log for more details
```

Gradle Console

```Executing tasks: [:cache:generateDebugSources, :cache:generateDebugAndroidTestSources, :cache:mockableAndroidJar, :mobile-ui:generateDebugSources, :mobile-ui:generateDebugAndroidTestSources, :mobile-ui:mockableAndroidJar, :presentation:generateDebugSources, :presentation:generateDebugAndroidTestSources, :presentation:mockableAndroidJar]

Configuration on demand is an incubating feature.
Configuration 'compile' in project ':mobile-ui' is deprecated. Use 'implementation' instead.
Configuration 'compile' in project ':presentation' is deprecated. Use 'implementation' instead.
'kapt.generateStubs' is not used by the 'kotlin-kapt' plugin
'kapt.generateStubs' is not used by the 'kotlin-kapt' plugin
'kapt.generateStubs' is not used by the 'kotlin-kapt' plugin
'kapt.generateStubs' is not used by the 'kotlin-kapt' plugin
:cache:preBuild UP-TO-DATE
:cache:preDebugBuild UP-TO-DATE
:cache:compileDebugAidl
:cache:compileDebugRenderscript
:cache:checkDebugManifest
:cache:generateDebugBuildConfig
:cache:generateDebugResValues
:cache:generateDebugResources
:cache:packageDebugResources
:cache:platformAttrExtractor
:cache:processDebugManifest
:cache:preDebugAndroidTestBuild UP-TO-DATE
:cache:compileDebugAndroidTestAidl
:cache:packageDebugRenderscript NO-SOURCE
:cache:processDebugAndroidTestManifest
:cache:compileDebugAndroidTestRenderscript
:cache:generateDebugAndroidTestBuildConfig
:cache:generateDebugAndroidTestResValues
:cache:generateDebugAndroidTestResources
:cache:mergeDebugAndroidTestResources
:cache:mockableAndroidJar
:mobile-ui:preBuild UP-TO-DATE
:presentation:preBuild UP-TO-DATE
:presentation:preDebugBuild UP-TO-DATE
:presentation:checkDebugManifest
:presentation:processDebugManifest
:mobile-ui:preDebugBuild
:presentation:compileDebugAidl
:mobile-ui:compileDebugAidl
:presentation:packageDebugRenderscript NO-SOURCE
:mobile-ui:compileDebugRenderscript
:mobile-ui:checkDebugManifest
:mobile-ui:generateDebugBuildConfig
:mobile-ui:generateDebugResValues
:mobile-ui:generateDebugResources
:presentation:compileDebugRenderscript
:presentation:generateDebugResValues
:presentation:generateDebugResources
:presentation:packageDebugResources
:mobile-ui:mergeDebugResources
:mobile-ui:createDebugCompatibleScreenManifests
:mobile-ui:processDebugManifest
:mobile-ui:splitsDiscoveryTaskDebug
:presentation:platformAttrExtractor
:cache:processDebugResources
:cache:generateDebugSources
:cache:processDebugAndroidTestResources
:cache:generateDebugAndroidTestSources
:mobile-ui:preDebugAndroidTestBuild
:mobile-ui:compileDebugAndroidTestAidl
:mobile-ui:processDebugAndroidTestManifest
:mobile-ui:compileDebugAndroidTestRenderscript
:mobile-ui:generateDebugAndroidTestBuildConfig
:mobile-ui:generateDebugAndroidTestResValues
:mobile-ui:generateDebugAndroidTestResources
:mobile-ui:mergeDebugAndroidTestResources
:mobile-ui:splitsDiscoveryTaskDebugAndroidTest
:mobile-ui:mockableAndroidJar
:presentation:generateDebugBuildConfig
:presentation:preDebugAndroidTestBuild UP-TO-DATE
:presentation:compileDebugAndroidTestAidl
:presentation:processDebugAndroidTestManifest
:presentation:compileDebugAndroidTestRenderscript
:presentation:generateDebugAndroidTestBuildConfig
:presentation:generateDebugAndroidTestResValues
:presentation:generateDebugAndroidTestResources
:presentation:mergeDebugAndroidTestResources
:presentation:mockableAndroidJar
:presentation:processDebugResources
:mobile-ui:processDebugResources
:mobile-ui:generateDebugSources
:mobile-ui:processDebugAndroidTestResources
:mobile-ui:generateDebugAndroidTestSources
:presentation:generateDebugSources
:presentation:processDebugAndroidTestResources
:presentation:generateDebugAndroidTestSources

BUİLD SUCCESSFUL in 9s
55 actionable tasks: 55 executed
Executing tasks: [:mobile-ui:assembleDebug]

Configuration 'compile' in project ':mobile-ui' is deprecated. Use 'implementation' instead.
Configuration 'compile' in project ':presentation' is deprecated. Use 'implementation' instead.
'kapt.generateStubs' is not used by the 'kotlin-kapt' plugin
'kapt.generateStubs' is not used by the 'kotlin-kapt' plugin
'kapt.generateStubs' is not used by the 'kotlin-kapt' plugin
'kapt.generateStubs' is not used by the 'kotlin-kapt' plugin
:cache:preBuild UP-TO-DATE
:cache:preDebugBuild UP-TO-DATE
:cache:compileDebugAidl UP-TO-DATE
:cache:compileDebugRenderscript UP-TO-DATE
:cache:checkDebugManifest UP-TO-DATE
:cache:generateDebugBuildConfig UP-TO-DATE
:cache:generateDebugResValues UP-TO-DATE
:cache:generateDebugResources UP-TO-DATE
:cache:packageDebugResources UP-TO-DATE
:cache:platformAttrExtractor UP-TO-DATE
:cache:processDebugManifest UP-TO-DATE
:cache:processDebugResources
:domain:compileKotlin
Using kotlin incremental compilation
:domain:compileJava NO-SOURCE
:domain:processResources NO-SOURCE
:domain:classes UP-TO-DATE
:domain:jar
:data:compileKotlin
Using kotlin incremental compilation
:data:compileJava NO-SOURCE
:data:processResources NO-SOURCE
:data:classes UP-TO-DATE
:data:jar
:cache:kaptGenerateStubsDebugKotlin
Using kotlin incremental compilation
:cache:kaptDebugKotlin
w: warning: Supported source version 'RELEASE_7' from annotation processor 'android.arch.persistence.room.RoomProcessor' less than -source '1.8'
w: 


e: C:\Proje\clean-architecture-components-boilerplate\cache\build\tmp\kapt3\stubs\debug\org\buffer\android\boilerplate\cache\model\CachedBufferoo.java:7: error: Cannot find getter for field.
e: 

e:     private long id;
e:                  ^

w: C:\Proje\clean-architecture-components-boilerplate\cache\build\tmp\kapt3\stubs\debug\org\buffer\android\boilerplate\cache\db\BufferoosDatabase.java:5: warning: Schema export directory is not provided to the annotation processor so we cannot export the schema. You can either provide `room.schemaLocation` annotation processor argument OR set exportSchema to false.
w: 

w: public abstract class BufferoosDatabase extends android.arch.persistence.room.RoomDatabase {
w:                 ^

e: java.lang.IllegalStateException: failed to analyze: org.jetbrains.kotlin.kapt3.diagnostic.KaptError: Error while annotation processing
	at org.jetbrains.kotlin.analyzer.AnalysisResult.throwIfError(AnalysisResult.kt:57)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules(KotlinToJVMBytecodeCompiler.kt:138)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:170)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:58)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:93)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:46)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:92)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$2.invoke(CompileServiceImpl.kt:386)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$2.invoke(CompileServiceImpl.kt:98)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:832)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:98)
	at org.jetbrains.kotlin.daemon.common.DummyProfiler.withMeasure(PerfUtils.kt:137)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.checkedCompile(CompileServiceImpl.kt:859)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.doCompile(CompileServiceImpl.kt:831)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:385)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:346)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.jetbrains.kotlin.kapt3.diagnostic.KaptError: Error while annotation processing
	at org.jetbrains.kotlin.kapt3.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:90)
	at org.jetbrains.kotlin.kapt3.AnnotationProcessingKt.doAnnotationProcessing$default(annotationProcessing.kt:42)
	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.runAnnotationProcessing(Kapt3Extension.kt:205)
	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.analysisCompleted(Kapt3Extension.kt:166)
	at org.jetbrains.kotlin.kapt3.ClasspathBasedKapt3Extension.analysisCompleted(Kapt3Extension.kt:82)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM$analyzeFilesWithJavaIntegration$2.invoke(TopDownAnalyzerFacadeForJVM.kt:96)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:106)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:83)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:377)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:68)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:96)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:368)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules(KotlinToJVMBytecodeCompiler.kt:133)
	... 30 more


:cache:kaptDebugKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cache:kaptDebugKotlin'.
> Internal compiler error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUİLD FAILED in 9s

15 actionable tasks: 7 executed, 8 up-to-date

```

**Comment by erluxman** [comment]
Remove` private` from   ` @PrimaryKey private Long id; ` . The annotation processor needs to be able to access the id filed to generate the necessary methods to do CRUD in database.
